# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sK8j8t5-FbDsHtWDLpnZDL4qNfoBQDKJ
"""

inp_str = "AssignmentDay2"
out = {x : inp_str.count(x) for x in set(inp_str )} 
print ("Occurrence of all characters in This Word is :\n "+ str(out))