# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXMJtwlIuKCKFTv7wPY3dTc2vy474w4D
"""

import math, random
def generateOTP() :
    digits = "0123456789"
    OTP = ""
    for i in range(6) :
        OTP += digits[math.floor(random.random() * 10)]
    return OTP
if __name__ == "__main__" :
    print("Your 6 Digit OTP Is:", generateOTP())